DEBUG = True
TRAP_HTTP_EXCEPTIONS = True
PROPAGATE_EXCEPTIONS = True
PRESERVE_CONTEXT_ON_EXCEPTION = True
HOST = '0.0.0.0'
USE_TIMS_API_KEYS = False
READ_FROM_FILES = False
WRITE_TO_FILE = False
TRAP_BAD_REQUEST_ERRORS = True
MAX_API_CALLS = 3
FILENAME = 'stations.txt'
OUTPUT_DIRECTORY = '/Users/tlowe/development/RunToTrain/output'

